version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django-extensions
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
  - dependency-name: asgiref
    versions:
    - 3.3.1
    - 3.3.2
  - dependency-name: pygments
    versions:
    - 2.7.4
    - 2.8.0
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: lazy-object-proxy
    versions:
    - 1.5.2
  - dependency-name: parso
    versions:
    - 0.8.1
